import {
  Home,
  ShoppingCart,
  Car,
  Zap,
  Heart,
  Tv,
  Shirt,
  BookOpen,
  Users,
  Smartphone,
  Sparkles,
  Gift,
  Landmark,
  Shield,
  TrendingUp,
  BarChart2,
  UserCheck,
  Rocket,
} from "lucide-react";

export const EXPENSE_CATEGORIES = [
  {
    id: "rent",
    label: "Rent/EMI",
    icon: Home,
    typical: 0.3,
    tip: "Ideally <= 30% of salary",
  },
  {
    id: "food",
    label: "Food & Groceries",
    icon: ShoppingCart,
    typical: 0.12,
    tip: "Cooking saves 40% vs eating out",
  },
  {
    id: "transport",
    label: "Transport & Fuel",
    icon: Car,
    typical: 0.07,
    tip: "Consider public transport",
  },
  {
    id: "utilities",
    label: "Utilities & Bills",
    icon: Zap,
    typical: 0.05,
    tip: "Electricity, internet, phone",
  },
  {
    id: "health",
    label: "Health & Medical",
    icon: Heart,
    typical: 0.05,
    tip: "Include insurance premium",
  },
  {
    id: "entertainment",
    label: "Entertainment & OTT",
    icon: Tv,
    typical: 0.04,
    tip: "Netflix, Swiggy, outings",
  },
  {
    id: "clothing",
    label: "Clothing & Shopping",
    icon: Shirt,
    typical: 0.04,
    tip: "Avg Indian spends ₹2-5K/mo",
  },
  {
    id: "education",
    label: "Education & Courses",
    icon: BookOpen,
    typical: 0.03,
    tip: "Best investment in yourself",
  },
  {
    id: "family",
    label: "Family Support",
    icon: Users,
    typical: 0.08,
    tip: "Remittances, parents, kids",
  },
  {
    id: "subscriptions",
    label: "Subscriptions",
    icon: Smartphone,
    typical: 0.02,
    tip: "All recurring monthly charges",
  },
  {
    id: "personal",
    label: "Personal Care",
    icon: Sparkles,
    typical: 0.03,
    tip: "Salon, gym, grooming",
  },
  {
    id: "misc",
    label: "Miscellaneous",
    icon: Gift,
    typical: 0.05,
    tip: "Gifts, emergencies, others",
  },
];
export const INVESTMENT_OPTIONS = [
  {
    id: "fd",
    label: "Fixed Deposit",
    icon: Landmark,
    rate: 7.0,
    risk: "Very Low",
    horizon: "1–3 yrs",
    color: "#4ecdc4",
    desc: "Safe, guaranteed returns. Best for short-term goals.",
  },
  {
    id: "ppf",
    label: "PPF",
    icon: Shield,
    rate: 7.1,
    risk: "Very Low",
    horizon: "15 yrs",
    color: "#45b7d1",
    desc: "Tax-free returns + Section 80C deduction. Govt-backed.",
  },
  {
    id: "mf",
    label: "Mutual Fund SIP",
    icon: TrendingUp,
    rate: 12.0,
    risk: "Moderate",
    horizon: "5+ yrs",
    color: "#00d4aa",
    desc: "Diversified equity funds. Historical avg ~12% CAGR.",
  },
  {
    id: "nifty",
    label: "Nifty 50 Index Fund",
    icon: BarChart2,
    rate: 13.5,
    risk: "Moderate",
    horizon: "7+ yrs",
    color: "#f5c842",
    desc: "Track India's top 50 companies. Low cost, high reward.",
  },
  {
    id: "nps",
    label: "NPS (Pension)",
    icon: UserCheck,
    rate: 10.0,
    risk: "Low–Moderate",
    horizon: "Till 60",
    color: "#a29bfe",
    desc: "Retirement corpus + extra ₹50K tax deduction.",
  },
  {
    id: "stocks",
    label: "Direct Stocks",
    icon: Rocket,
    rate: 16.0,
    risk: "High",
    horizon: "10+ yrs",
    color: "#fd79a8",
    desc: "High risk, potentially highest reward. Research needed.",
  },
];
export const GOAL_OPTIONS = [
  "House",
  "Car",
  "Retirement",
  "Emergency Fund",
  "Travel",
  "Education",
  "Business",
];

export const RISK_OPTIONS = [
  {
    id: "conservative",
    label: "Conservative",
    desc: "Safety first. FD, PPF, bonds.",
  },
  {
    id: "moderate",
    label: "Moderate",
    desc: "Balanced growth. Mix of MF + FD.",
  },
  {
    id: "aggressive",
    label: "Aggressive",
    desc: "Max returns. Stocks, Index funds.",
  },
];
